require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
AbcSize:
  Exclude:
    - 'db/migrate/*'
MethodLength:
  Exclude:
    - 'db/migrate/*'
